### ISSUE TITLE
styling issues

### ISSUE THREAD

**Issue by kartikeya23** [nirbhay-py/TuringTestFrontEnd#1]
<img width="1331" alt="Screenshot 2019-10-17 at 9 02 39 PM" src="https://user-images.githubusercontent.com/24318731/67024178-99ea6180-f121-11e9-9c87-f8a8af04dd20.png">

- the text sizes are different for the entry fields and labels
- there are two cursors and its confusing

just a question:
- can we have up-down arrow keys switching between the two entry fields?

**Comment by nirbhay-py** [comment]
1.put border on text field to make it visible 
2. removed cursor
3. fixed text size
4. added up/down arrow functionality - could not get them to switch between the fields i.e. pressing the up key will add focus on the username field only, it will not alternate between the fields
5. put text fields on new lines
6. added login button
